name: Nordlys CI

on:
  push:
    branches: [main]
    paths:
      - "nordlys/**"
      - ".github/workflows/nordlys-ci.yml"
      - ".github/workflows/nordlys-test.yml"
  pull_request:
    branches: [main]
    paths:
      - "nordlys/**"
      - ".github/workflows/nordlys-ci.yml"
      - ".github/workflows/nordlys-test.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/nordlys-test.yml
